### ISSUE TITLE
Scroll Stuck in Support Library 26

### ISSUE THREAD

**Issue by anup1245** [cesardeazevedo/react-native-nested-scroll-view#16] opened 2018-01-05 02:29 UTC
On fling, the scroll gets stuck to end of the list.
Happening on Support Library 26

**Comment by ddenisen** [comment] 2018-01-11 02:23
I am seeing the same issue

**Comment by cesardeazevedo** [comment] 2018-01-11 09:41
Without any way that i could to reproduce it, i don't know how to help, the library is too generic, i don't know how people are exactly using it.

If there's any project example that i could reproduce it, i might take a look.

**Comment by ddenisen** [comment] 2018-01-11 19:27
Thanks for the response; I am going to try to create and share a sample project if I have time.

For the record, here is my config:
* RN 0.49.0
* `react-native-nested-scroll-view` 5.0.2
* `compileSdk=26`, `targetSdk=23`, `minSdk=19` (we can't target 26 yet for other reasons, specifically RN seems to not be fully compatible with it)
* Support libraries 26.1.0

In our app, we have a scroll view that is nested inside another, full-screen scroll view. The nested scroll view has at least several pages worth of content. Once I scroll the nested view all the way to the bottom, I have to be very slow when scrolling up; any fling or rapid scroll of the nested view forces it to instantly reposition its content to the very end.

Rolling the support libraries back to 25.4.0 while keeping the rest of the dependencies/config the same fixes the issue.

**Comment by JaxGit** [comment] 2018-06-04 05:15
@anup1245 @ddenisen @cesardeazevedo  We've just encountered the same issue when one of my colleague updated his phone's firmware version while keeping on Android 8.0.0 yesterday, but it was working fine before that. Also all of my other colleagues on Android 8 don't have this issue. 

So the known breaking versions of our case are:
Mobel: BLA-L09 8.0.0.134(C34), Android OS: 8.0.0

Environments:
RN 0.51.0
react-native-nested-scroll-view: 6.0.1
compileSdkVersion 24
buildToolsVersion '24.0.0'
minSdkVersion 19
targetSdkVersion 24
compile 'com.android.support:appcompat-v7:23.0.1'

Unexpected behaviour:
When momentum scrolling up/down, any ScrollView immediately scrolls to the end, onMomentumScrollBegin/onMomentumScrollEnd immediately fire without any interval.

**Comment by aforian** [comment] 2018-06-20 08:37
@JaxGit  @ddenisen I saw the same issue too and I get fixed in #14 .
in `ReactNesetdScrollView.java`:
```
@Override
  public void fling(int velocityY) {
    super.fling(velocityY);  //add this line

    ....
}
```
then run-android again
NestedScroll works perfectlly.

**Comment by itsaju** [comment] 2018-06-20 10:05
Hi aforian,
I am facing the same issue after certain point scrolling upwards is not working properly.
By adding super.fling(velocityY); my issue got fixed. 
Thanks in advance.

Great Library. Helped a lot with nested scroll issue @cesardeazevedo .

**Comment by cesardeazevedo** [comment] 2018-07-16 09:21
Thanks so much for all the comments, after i update the library to work with support library 26, i could clearly see the issue. 🎉 

This issue has been highly reported (#6, #14, #16), but i wasn't be able to reproduce it since i hadn't used support library 26, **so i really apologize**.

I will merge #20 and make a new release soon.

**Closed as completed** 2018-07-16 09:34 UTC
